### PR TITLE
Option types

### PR DESCRIPTION
**Pull request by shikaan**
## General info

**Type of issue:**  ENHANCEMENT

## Problem
#37 

## Solution
Add missing types and reshape a bit the structure of the declaration file

### CODE REVIEW

**Comment by lukaszmn** [comment]
Hi, thanks for trying to fix it. The idea with namespace did not really work for me - the global functions (`suite`, `spec`) were not recognized in VS Code.

The following solution worked, though:
```js
interface SuiteOptions {
  silent?: boolean,
  setup?: () => void,
  teardown?: () => void,
  eachSetup?: () => void,
  eachTeardown?: () => void
}

declare function xit(name: string, callback: Function): void;
declare function it(name: string, callback: Function): void;
declare function test(name: string, callback: Function): void;
declare function xtest(name: string, callback: Function): void;
declare function spec(name: string, callback: Function): void;
declare function xspec(name: string, callback: Function): void;

declare function suite(name: string, callback: Function): void;
declare function suite(name: string, options: SuiteOptions, callback: Function): void;

declare function describe(name: string, callback: Function): void;
declare function describe(name: string, options: SuiteOptions, callback: Function): void;
```

This is similar to the approach done in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/index.d.ts

**Comment by lukaszmn** [comment]
I'm not proficient in writing definition files, but the docs may be helpful:
http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by shikaan** [comment]
The namespace solution seems to be working in WebStorm
image
and to be honest I would prefer that, rather than polluting the global namespace....

What was exactly the problem for you?

**Comment by lukaszmn** [comment]
I know what's the cause. Previously I used Titef without any imports in test files and it worked great.

The solution with a namespace (this PR) works only after I import Titef with the line:
```
const { suite, spec } = require('titef');
```

Assuming that's the suggested way to use Titef, I think you can merge it.

**Comment by shikaan** [comment]
With latest commit we should be getting both working (global and imported). I have given that a shot on VSCode and seems to be okay as well. 

Please let me know whether that's working for you.

Thanks again! :tada:

**Comment by lukaszmn** [comment]
Thanks. It still doesn't work if I don't import anything, because you ended the file with `export = titef`. Anyway. I took some time to check the competition and the documentation and I can share my findings:

1. I personally don't like the idea of duplicating definitions in the namespace and outside. You should decide whether you add functions to the global namespace or create own namespace. Mixing both yields confusion.
2. If I understood the [docs](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#1215-ambient-namespace-declarations), `export` makes no difference in an ambient namespace (`declare namespace`), so you can drop it.
3. I dislike labeling functions with `var`. All guides suggest to use `function`:
    * https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#global-functions
    * https://definitelytyped.org/guides/best-practices.html
4. I think it is not a bad idea to follow working solutions of bigger frameworks, like AVA (import), Jest (global), jasmine (global), mocha (global), etc., and 

As always, the final decision is up to you ;).

**Comment by shikaan** [comment]
Hey there,

Can you tell me exactly how are you testing it? I really cannot see how this cannot work as it stands currently. Maybe the setup makes a difference here?

I am running on Debian 9 and Webstorm 2019.3.2/VSCode 1.41.1

1. The framework is meant to work the same way when using the CLI or using it programmatically, hence I think there is no point in making this decision for the user. Especially if the reason behind the choice is just the `*.d.ts` file;

2. You are right, but the documentation also mentions that it is harmless. I don't think that's related to your problems;

3. There's unfortunately no way to use the `function` keyword with `interface`s. Given that one of the main selling point of this framework is the facility to migrate from other libraries easily. Therefore, I see the list of methods implementing the `SuiteFunction` and the `SpecFunction` interfaces growing over time, making the duplication a bigger problem down the line.

4. I am actually using one of the templates provided by TypeScript team themselves

**Comment by lukaszmn** [comment]
Hi, I use Windows 10, VS Code 1.41.1, Node v10.16.2.

I installed Titef and replaced *node_modules\titef\dist\types.d.ts* with [latest commit](https://raw.githubusercontent.com/shikaan/titef/a703aba3ee04199c3500821102a968b6f3b0f5cc/dist/types.d.ts).

I have *test.js* in the root directory with contents:

```js
// const { suite, spec } = require('titef');
...

suite('delete folder', {
	eachSetup() {
		mock.restore();
	},
}, () => {
```

(The source is temporarily available at https://github.com/lukaszmn/Simple-Build-Kit/tree/titef).

VS highlights `suite` and `spec` as unrecognized functions.

**Comment by shikaan** [comment]
Hey there, finally got a PC in my hands to work with :D

So I think the problem is with how you are conducting the test: usually `node_modules` folders are ignored or generally speaking get a different treatment by the IDE. This actually gets worse if you manually tinker with the files in such folder.

A more useful test in my eyes (which is eventually closer to what happens when we deploy the package) is the following:
* clone the repo
* switch to the `option-types` branch
* run a build
* run `npm link $PATH_TO_TITEF`

You should be seeing it working in this case. I have got the chance to test it also on a MacBook and another Linux machine and it seems to be working fine.

Let me know how it goes and apologies again for the delay

**Comment by shikaan** [comment]
Also, I have cloned your project and it works there as well, as long as you remove the `ts-ignore` annotation.

**Comment by lukaszmn** [comment]
Hi, I did as you instructed, and:
* the IntelliSense works (suggests two variants of `suite()`)
* then the `suite` word is underlined as an unknown function
* but the test executes

So it's still not a perfect solution in my env, unless I do something wrong...

**Comment by shikaan** [comment]
Did you try to restart VSCode or refresh the file list after the `npm link`? Sounds so strange that you get the intellisense working, but it's still recognized as unknown function.

Let me know if this helps you and if we close this issue. 

Thanks again!

**Comment by lukaszmn** [comment]
Yes, I refreshed and restarted. I agree it's strange, likely a bug in VS Code.

Summarizing, I still cannot use `suite` without importing it's first. But I'm fine with it. It would be great if this test was performed on another Windows machine.

**Comment by shikaan** [comment]
> Summarizing, I still cannot use suite without importing it's first.

Why is that so? Having it underlined in the IDE should hinder code execution... 
Are you sure there's nothing like a linter, a VSCode extensions or something like that in the way here? Maybe you should give it a go disabling all the extensions and restarting?

I suggest we keep this open for a couple of other days, should someone pop by to the rescue with a Windows machine

**Comment by lukaszmn** [comment]
I disabled all extensions and restarted, same effect. VS Code 1.42.1, Win 10.

**Comment by shikaan** [comment]
But, again, how is this preventing you to run code? What is the error you get?

**Comment by shikaan** [comment]
Merging for now. We can rework it later if needed.

Closes #37

**Comment by lukaszmn** [comment]
It does not prevent me from running. I just get nasty error highlights in the editor ;). I'll check again after I use the new version from npm.

**Pull request merged**
